from django.db import models
"""
@author Hanabi (autogenerated)
This model was generated on Saturday 19. November 2011 01:53:02
DO NOT MODIFY!!! 
"""


# --------- BEGIN MODEL DEFINITION ---------
class personality(models.Model):
    # Represents the possible values for each survey question
    # The numbers are what will be seen 
     
#    ------ BEGIN ATTRIBUTES -----    #
#    *** QUESTION 0 How DEPENDABLE are you?***    
    choices0 = ((-2.0, "Not at all"), (-1.0, "Not so much"), (0.0, "Somewhat"), (1.0, "Reasonably"), (2.0, "Very"),)
    query0 = models.IntegerField(default = 0, choices = choices0)
#    *** QUESTION 1 How MILD-MANNERED are you?***    
    choices1 = ((-2.0, "Not at all"), (-1.0, "Not so much"), (0.0, "Somewhat"), (1.0, "Reasonably"), (2.0, "Very"),)
    query1 = models.IntegerField(default = 0, choices = choices1)
#    *** QUESTION 2 How much of a LEADER are you?***    
    choices2 = ((-2.0, "Not at all"), (-1.0, "Not so much"), (0.0, "Somewhat"), (1.0, "Reasonably"), (2.0, "Very"),)
    query2 = models.IntegerField(default = 0, choices = choices2)
#    *** QUESTION 3 How EMPATHETIC are you?***    
    choices3 = ((-2.0, "Not at all"), (-1.0, "Not so much"), (0.0, "Somewhat"), (1.0, "Reasonably"), (2.0, "Very"),)
    query3 = models.IntegerField(default = 0, choices = choices3)
#    *** QUESTION 4 How SYMPATHETIC are you?***    
    choices4 = ((-2.0, "Not at all"), (-1.0, "Not so much"), (0.0, "Somewhat"), (1.0, "Reasonably"), (2.0, "Very"),)
    query4 = models.IntegerField(default = 0, choices = choices4)
#    *** QUESTION 5 How DETAIL-ORIENTED are you?***    
    choices5 = ((-2.0, "Not at all"), (-1.0, "Not so much"), (0.0, "Somewhat"), (1.0, "Reasonably"), (2.0, "Very"),)
    query5 = models.IntegerField(default = 0, choices = choices5)
#    *** QUESTION 6 How OPEN-MINDED are you?***    
    choices6 = ((-2.0, "Not at all"), (-1.0, "Not so much"), (0.0, "Somewhat"), (1.0, "Reasonably"), (2.0, "Very"),)
    query6 = models.IntegerField(default = 0, choices = choices6)
#    *** QUESTION 7 How EXTRAVERTED are you?***    
    choices7 = ((-2.0, "Not at all"), (-1.0, "Not so much"), (0.0, "Somewhat"), (1.0, "Reasonably"), (2.0, "Very"),)
    query7 = models.IntegerField(default = 0, choices = choices7)
#    *** QUESTION 8 How AGREEABLE are you?***    
    choices8 = ((-2.0, "Not at all"), (-1.0, "Not so much"), (0.0, "Somewhat"), (1.0, "Reasonably"), (2.0, "Very"),)
    query8 = models.IntegerField(default = 0, choices = choices8)
#    *** QUESTION 9 How PASSIONATE are you?***    
    choices9 = ((-2.0, "Not at all"), (-1.0, "Not so much"), (0.0, "Somewhat"), (1.0, "Reasonably"), (2.0, "Very"),)
    query9 = models.IntegerField(default = 0, choices = choices9)
#    *** QUESTION 10 How SELFLESS are you?***    
    choices10 = ((-2.0, "Not at all"), (-1.0, "Not so much"), (0.0, "Somewhat"), (1.0, "Reasonably"), (2.0, "Very"),)
    query10 = models.IntegerField(default = 0, choices = choices10)
#    ------ END ATTRIBUTES -----     
#--------- END MODEL DEFINITION ----------
