from django.db import models
"""
@author Hanabi (autogenerated)
# This model was generated on Friday 18. November 2011 20:09:14
# DO NOT MODIFY!!! 
"""


# --------- BEGIN MODEL DEFINITION ---------
class food(models.Model):
    # Represents the possible values for each survey question
    # The numbers are what will be seen 
     
#    ------ BEGIN ATTRIBUTES -----    #
#    *** QUESTION 0 ***    
    choices0 = ((-2.0, "Hate it!"), (-1.0, "Don't care for it"), (0.0, "Neutral"), (1.0, "Like it"), (2.0, "Love it!"),)
    query0 = models.IntegerField(default = 0, choices = choices0)
#    *** QUESTION 1 ***    
    choices1 = ((-2.0, "Hate it!"), (-1.0, "Don't care for it"), (0.0, "Neutral"), (1.0, "Like it"), (2.0, "Love it!"),)
    query1 = models.IntegerField(default = 0, choices = choices1)
#    *** QUESTION 2 ***    
    choices2 = ((-2.0, "Hate it!"), (-1.0, "Don't care for it"), (0.0, "Neutral"), (1.0, "Like it"), (2.0, "Love it!"),)
    query2 = models.IntegerField(default = 0, choices = choices2)
#    *** QUESTION 3 ***    
    choices3 = ((-2.0, "Hate it!"), (-1.0, "Don't care for it"), (0.0, "Neutral"), (1.0, "Like it"), (2.0, "Love it!"),)
    query3 = models.IntegerField(default = 0, choices = choices3)
#    *** QUESTION 4 ***    
    choices4 = ((-2.0, "Hate it!"), (-1.0, "Don't care for it"), (0.0, "Neutral"), (1.0, "Like it"), (2.0, "Love it!"),)
    query4 = models.IntegerField(default = 0, choices = choices4)
#    *** QUESTION 5 ***    
    choices5 = ((-2.0, "Hate it!"), (-1.0, "Don't care for it"), (0.0, "Neutral"), (1.0, "Like it"), (2.0, "Love it!"),)
    query5 = models.IntegerField(default = 0, choices = choices5)
#    *** QUESTION 6 ***    
    choices6 = ((-2.0, "Hate it!"), (-1.0, "Don't care for it"), (0.0, "Neutral"), (1.0, "Like it"), (2.0, "Love it!"),)
    query6 = models.IntegerField(default = 0, choices = choices6)
#    *** QUESTION 7 ***    
    choices7 = ((-2.0, "None"), (-1.0, "Not much"), (0.0, "Moderate"), (1.0, "Quite a bit"), (2.0, "Cant get enough of the stuff"),)
    query7 = models.IntegerField(default = 0, choices = choices7)
#    *** QUESTION 8 ***    
    choices8 = ((-2.0, "None"), (-1.0, "Not much"), (0.0, "Moderate"), (1.0, "Quite a bit"), (2.0, "Cant get enough of it"),)
    query8 = models.IntegerField(default = 0, choices = choices8)
#    *** QUESTION 9 ***    
    choices9 = ((-2.0, "None"), (-1.0, "Not much"), (0.0, "Moderate"), (1.0, "Quite a bit"), (2.0, "Cant get enough of it"),)
    query9 = models.IntegerField(default = 0, choices = choices9)
#    *** QUESTION 10 ***    
    choices10 = ((-2.0, "None"), (-1.0, "Not much"), (0.0, "Moderate"), (1.0, "Quite a bit"), (2.0, "Cant get enough of it"),)
    query10 = models.IntegerField(default = 0, choices = choices10)
#    *** QUESTION 11 ***    
    choices11 = ((-2.0, "None"), (-1.0, "Not much"), (0.0, "Moderate"), (1.0, "Quite a bit"), (2.0, "Cant get enough of it"),)
    query11 = models.IntegerField(default = 0, choices = choices11)
#    *** QUESTION 12 ***    
    choices12 = ((-2.0, "None"), (-1.0, "Not much"), (0.0, "Moderate"), (1.0, "Quite a bit"), (2.0, "Cant get enough of it"),)
    query12 = models.IntegerField(default = 0, choices = choices12)
#    *** QUESTION 13 ***    
    choices13 = ((-2.0, "None"), (-1.0, "Not much"), (0.0, "Moderate"), (1.0, "Quite a bit"), (2.0, "Cant get enough of it"),)
    query13 = models.IntegerField(default = 0, choices = choices13)
#    *** QUESTION 14 ***    
    choices14 = ((-2.0, "None"), (-1.0, "Not much"), (0.0, "Moderate"), (1.0, "Quite a bit"), (2.0, "Cant get enough of it"),)
    query14 = models.IntegerField(default = 0, choices = choices14)
#    *** QUESTION 15 ***    
    choices15 = ((-1.0, "COFFEE"), (0.0, "NEITHER"), (1.0, "TEA"),)
    query15 = models.IntegerField(default = 0, choices = choices15)
#    ------ END ATTRIBUTES -----     
