from django.db import models
"""
@author Hanabi (autogenerated)
# This model was generated on Friday 18. November 2011 20:09:07
# DO NOT MODIFY!!! 
"""


# --------- BEGIN MODEL DEFINITION ---------
class health(models.Model):
    # Represents the possible values for each survey question
    # The numbers are what will be seen 
     
#    ------ BEGIN ATTRIBUTES -----    #
#    *** QUESTION 0 ***    
    choices0 = ((-1.0, "None"), (0.0, "Light"), (1.0, "Moderate"), (2.0, "Severe"),)
    query0 = models.IntegerField(default = 0, choices = choices0)
#    *** QUESTION 1 ***    
    choices1 = ((-1.0, "None"), (0.0, "Light"), (1.0, "Moderate"), (2.0, "Severe"),)
    query1 = models.IntegerField(default = 0, choices = choices1)
#    *** QUESTION 2 ***    
    choices2 = ((-1.0, "None"), (0.0, "Light"), (1.0, "Moderate"), (2.0, "Severe"),)
    query2 = models.IntegerField(default = 0, choices = choices2)
#    *** QUESTION 3 ***    
    choices3 = ((-1.0, "Not at all"), (0.0, "Light"), (1.0, "Moderate"), (2.0, "Heavy"),)
    query3 = models.IntegerField(default = 0, choices = choices3)
#    *** QUESTION 4 ***    
    choices4 = ((-2.0, "Never"), (-1.0, "Not very"), (0.0, "Once in a while"), (1.0, "Regularly"), (2.0, "Very"),)
    query4 = models.IntegerField(default = 0, choices = choices4)
#    *** QUESTION 5 ***    
    choices5 = ((-1.0, "Only juice and Mountain Dew for me"), (0.0, "Not much"), (1.0, "Water is life "),)
    query5 = models.IntegerField(default = 0, choices = choices5)
#    ------ END ATTRIBUTES -----     
